l10n_ch_payment_slip: Fix README error when generating missing terms (translations)
Without this Odoo raises following error:
File "/.repo_requirements/odoo/odoo/tools/translate.py", line 464, in quote
    assert r"\n" not in s, "Translation terms may not include escaped newlines ('\\n'), please use only literal newlines! (in '%s')" % s
AssertionError: Translation terms may not include escaped newlines ('\n'), please use only literal newlines! (in